import type { NextPage } from 'next';
import Head from 'next/head';
import Masthead from '../components/masthead';
import AboutUs from '../components/aboutus';
import Skills from '../components/skills';
import Works from '../components/works';
import TrustedBy from '../components/trustedby';
import ContactUs from '../components/contactus';
import Footer from '../components/footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TWB - The Work Bazaar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      <script src="https://static.elfsight.com/platform/platform.js" data-use-service-core defer></script>
      </Head>
<div className="elfsight-app-0e60726f-f1fd-4da4-90d8-2e9a8083ca5b"></div>

      <Masthead />
      <Skills />
      <Works />
      <AboutUs />
      <TrustedBy />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
